### ISSUE TITLE
ohai solo is no longer available

### ISSUE THREAD

**Issue by seanorama** [rackerlabs/ohai-plugins#170]
It appears the installer is no longer accessible:

```
# curl http://ohai.rax.io/install.sh
<html><h1>Not Found</h1><p>The resource could not be found.</p></html>
```

**Comment by ryandub** [comment]
Yes, unfortunately we aren't really working on this anymore. I will make a note to update the readme - apologies for the staleness.

You should still be able to use these ohai plugins if you need them, but the ohai-solo packages haven't been built in over a year at least.
